import type { MenuData } from '@/models/menu'
import type { PageLayout } from '@/models/layout'
import { createDefaultPageLayout, createDefaultTypography, createDefaultFontStyle, createDefaultColorScheme } from '@/models/layout'
import { nanoid } from 'nanoid'
import cafeTemplate from './cafe'
import pizzeriaTemplate from './pizzeria'
import sushiTemplate from './sushi'
import bakeryTemplate from './bakery'
import taqueriaTemplate from './taqueria'

export interface MenuTemplate {
  id: string
  name: string
  category: 'cocktail' | 'dinner' | 'wine' | 'brunch' | 'beer' | 'dessert' | 'table-tent' | 'blank' | 'cafe' | 'pizzeria' | 'sushi' | 'bakery' | 'taqueria'
  description: string
  tags?: string[]
  menuData: MenuData
  pageLayout: PageLayout
}

const templates: MenuTemplate[] = [
  // 1. Cocktail Bar
  {
    id: nanoid(),
    name: 'Cocktail Bar',
    category: 'cocktail',
    description: 'Sophisticated cocktail menu with signature drinks and classics',
    tags: ['dark-theme', 'elegant', 'multi-section'],
    menuData: {
      title: 'Cocktail Menu',
      subtitle: 'Handcrafted Libations',
      footer: '',
      sections: [
        {
          id: nanoid(),
          title: 'Signature Cocktails',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Midnight Manhattan',
              description: 'Rye whiskey, sweet vermouth, black walnut bitters, luxardo cherry',
              price: '16.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Lavender Fizz',
              description: 'Gin, house-made lavender syrup, fresh lemon, prosecco',
              price: '14.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Spicy Mezcal Margarita',
              description: 'Mezcal, jalapeño-infused agave, lime, smoked salt rim',
              price: '15.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Elderflower Garden',
              description: 'Vodka, elderflower liqueur, cucumber, mint, tonic',
              price: '14.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Bourbon Bramble',
              description: 'Bourbon, blackberry purée, lemon, crème de mûre float',
              price: '16.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Classic Cocktails',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Old Fashioned',
              description: 'Bourbon or rye, sugar, angostura bitters, orange twist',
              price: '14.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Negroni',
              description: 'Gin, Campari, sweet vermouth, orange peel',
              price: '13.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Espresso Martini',
              description: 'Vodka, coffee liqueur, fresh espresso, vanilla',
              price: '15.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'French 75',
              description: 'Gin, lemon juice, simple syrup, champagne',
              price: '16.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Non-Alcoholic',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Botanical Spritz',
              description: 'Non-alcoholic aperitif, tonic, fresh herbs, citrus',
              price: '8.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Ginger Mule',
              description: 'House-made ginger beer, lime, mint, cucumber',
              price: '7.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Berry Shrub',
              description: 'Mixed berry vinegar shrub, sparkling water, basil',
              price: '8.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
      ],
    },
    pageLayout: {
      ...createDefaultPageLayout(),
      pageSize: 'letter',
      orientation: 'portrait',
      margins: { top: 0.625, right: 0.52, bottom: 0.625, left: 0.52 },
      sectionLayouts: [],
      colorScheme: {
        background: '#1a1a2e',
        text: '#e0d6c8',
        accent: '#c9a96e',
        border: '#3d3d5c',
      },
      typography: {
        ...createDefaultTypography(),
        menuTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Playfair Display',
          fontSize: 48,
          fontWeight: 700,
          color: '#c9a96e',
          textAlign: 'center',
        },
        menuSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Playfair Display',
          fontSize: 18,
          fontWeight: 400,
          color: '#e0d6c8',
          letterSpacing: 2,
          textAlign: 'center',
        },
        sectionTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Playfair Display',
          fontSize: 24,
          fontWeight: 600,
          color: '#c9a96e',
        },
        sectionSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 12,
          fontWeight: 400,
          color: '#e0d6c8',
        },
        itemName: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 16,
          fontWeight: 600,
          color: '#e0d6c8',
        },
        itemDescription: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 13,
          fontWeight: 400,
          color: '#b8ae9e',
        },
        itemPrice: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 16,
          fontWeight: 700,
          color: '#c9a96e',
          textAlign: 'right',
        },
        footer: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 9,
          fontWeight: 400,
          color: '#b8ae9e',
          textAlign: 'center',
        },
      },
      itemSeparator: 'none',
      priceFormat: 'right-aligned',
    },
  },

  // 2. Fine Dining
  {
    id: nanoid(),
    name: 'Fine Dining',
    category: 'dinner',
    description: 'Elegant multi-course menu for upscale dining establishments',
    tags: ['light-theme', 'elegant', 'multi-section'],
    menuData: {
      title: 'Dinner Menu',
      subtitle: 'Seasonal Tasting Experience',
      footer: '',
      sections: [
        {
          id: nanoid(),
          title: 'Starters',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Seared Foie Gras',
              description: 'Hudson Valley foie gras, fig compote, brioche, aged balsamic',
              price: '24.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Diver Scallops',
              description: 'Pan-seared scallops, cauliflower purée, brown butter, caviar',
              price: '22.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Heirloom Tomato Tart',
              description: 'Puff pastry, burrata, heirloom tomatoes, basil oil, microgreens',
              price: '18.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Lobster Bisque',
              description: 'Maine lobster, cognac, tarragon cream, puff pastry dome',
              price: '20.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Mains',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Wagyu Beef Tenderloin',
              description: '8oz Japanese A5 wagyu, potato pavé, wild mushrooms, red wine reduction',
              price: '68.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Duck Breast',
              description: 'Roasted duck breast, cherry gastrique, duck fat fingerlings, frisée',
              price: '42.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Chilean Sea Bass',
              description: 'Miso-glazed sea bass, forbidden rice, bok choy, shiitake dashi',
              price: '48.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Rack of Lamb',
              description: 'Herb-crusted lamb, ratatouille, goat cheese polenta, lamb jus',
              price: '52.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Wild Mushroom Risotto',
              description: 'Carnaroli rice, porcini, truffle oil, parmigiano-reggiano, crispy sage',
              price: '32.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Sides',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Truffle Pommes Frites',
              description: 'Hand-cut fries, white truffle oil, parmesan, herbs',
              price: '12.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Grilled Broccolini',
              description: 'Charred broccolini, lemon, garlic, chili flakes',
              price: '10.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Creamed Spinach',
              description: 'Wilted spinach, heavy cream, nutmeg, gruyère',
              price: '11.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Desserts',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Chocolate Soufflé',
              description: 'Valrhona dark chocolate soufflé, vanilla bean crème anglaise',
              price: '16.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Lemon Tart',
              description: 'Meyer lemon curd, Italian meringue, raspberry coulis, shortbread',
              price: '14.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Crème Brûlée',
              description: 'Classic vanilla bean custard, caramelized sugar, fresh berries',
              price: '13.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
      ],
    },
    pageLayout: {
      ...createDefaultPageLayout(),
      pageSize: 'letter',
      orientation: 'portrait',
      margins: { top: 0.625, right: 0.57, bottom: 0.625, left: 0.57 },
      sectionLayouts: [],
      colorScheme: {
        background: '#FFFEF7',
        text: '#1a1a1a',
        accent: '#4a4a4a',
        border: '#d0d0d0',
      },
      typography: {
        ...createDefaultTypography(),
        menuTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Cormorant Garamond',
          fontSize: 52,
          fontWeight: 600,
          color: '#1a1a1a',
          textAlign: 'center',
        },
        menuSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Cormorant Garamond',
          fontSize: 16,
          fontWeight: 400,
          color: '#4a4a4a',
          letterSpacing: 3,
          textAlign: 'center',
        },
        sectionTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Cormorant Garamond',
          fontSize: 26,
          fontWeight: 600,
          color: '#1a1a1a',
        },
        sectionSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 12,
          fontWeight: 400,
          color: '#4a4a4a',
        },
        itemName: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 15,
          fontWeight: 500,
          color: '#1a1a1a',
        },
        itemDescription: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 12,
          fontWeight: 400,
          color: '#6a6a6a',
        },
        itemPrice: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 15,
          fontWeight: 600,
          color: '#1a1a1a',
          textAlign: 'right',
        },
        footer: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 9,
          fontWeight: 400,
          color: '#6a6a6a',
          textAlign: 'center',
        },
      },
      itemSeparator: 'none',
      priceFormat: 'right-aligned',
    },
  },

  // 3. Wine List
  {
    id: nanoid(),
    name: 'Wine List',
    category: 'wine',
    description: 'Curated wine selection with bottle and glass pricing',
    tags: ['light-theme', 'elegant', 'multi-section'],
    menuData: {
      title: 'Wine List',
      subtitle: 'Carefully Selected Vintages',
      footer: '',
      sections: [
        {
          id: nanoid(),
          title: 'Sparkling',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Veuve Clicquot Brut',
              description: 'Champagne, France • Crisp apple, brioche, persistent bubbles',
              price: '95.00',
              priceLabel: 'Glass $22',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Prosecco Superiore DOCG',
              description: 'Valdobbiadene, Italy • Pear, white flowers, refreshing finish',
              price: '48.00',
              priceLabel: 'Glass $12',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Schramsberg Blanc de Blancs',
              description: 'Napa Valley, USA • Citrus, toasted almond, elegant mousse',
              price: '72.00',
              priceLabel: 'Glass $18',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'White Wines',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Chablis Premier Cru',
              description: 'Burgundy, France • Flinty minerality, green apple, vibrant acidity',
              price: '68.00',
              priceLabel: 'Glass $16',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Cloudy Bay Sauvignon Blanc',
              description: 'Marlborough, New Zealand • Passion fruit, citrus, herbaceous notes',
              price: '52.00',
              priceLabel: 'Glass $14',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Rombauer Chardonnay',
              description: 'Carneros, USA • Butter, vanilla oak, ripe pineapple, creamy texture',
              price: '75.00',
              priceLabel: 'Glass $18',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Dr. Loosen Riesling',
              description: 'Mosel, Germany • Peach, honey, slate, off-dry balance',
              price: '46.00',
              priceLabel: 'Glass $12',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Red Wines',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Château Margaux',
              description: 'Bordeaux, France • Cassis, violet, cedar, silky tannins',
              price: '420.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Caymus Cabernet Sauvignon',
              description: 'Napa Valley, USA • Blackberry, mocha, vanilla, bold structure',
              price: '145.00',
              priceLabel: 'Glass $32',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Barolo DOCG',
              description: 'Piedmont, Italy • Cherry, rose, tar, firm tannins, long finish',
              price: '110.00',
              priceLabel: 'Glass $26',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Côtes du Rhône Villages',
              description: 'Rhône Valley, France • Raspberry, garrigue, pepper, earthy',
              price: '44.00',
              priceLabel: 'Glass $11',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Malbec Reserva',
              description: 'Mendoza, Argentina • Plum, blackberry, smoke, velvety finish',
              price: '52.00',
              priceLabel: 'Glass $13',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Dessert Wines',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Château d\'Yquem Sauternes',
              description: 'Bordeaux, France • Honeyed apricot, botrytis complexity, endless finish',
              price: '285.00',
              priceLabel: 'Glass $48',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Quinta do Noval Tawny Port',
              description: 'Douro, Portugal • Dried fig, caramel, walnut, 20 year aged',
              price: '98.00',
              priceLabel: 'Glass $18',
              tags: [],
              isAvailable: true,
            },
          ],
        },
      ],
    },
    pageLayout: {
      ...createDefaultPageLayout(),
      pageSize: 'letter',
      orientation: 'portrait',
      margins: { top: 0.625, right: 0.52, bottom: 0.625, left: 0.52 },
      sectionLayouts: [],
      colorScheme: {
        background: '#FFFDF5',
        text: '#2d1b2e',
        accent: '#722f37',
        border: '#d4c5a9',
      },
      typography: {
        ...createDefaultTypography(),
        menuTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'EB Garamond',
          fontSize: 50,
          fontWeight: 600,
          color: '#722f37',
          textAlign: 'center',
        },
        menuSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'EB Garamond',
          fontSize: 16,
          fontWeight: 400,
          color: '#2d1b2e',
          letterSpacing: 2.5,
          textAlign: 'center',
        },
        sectionTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'EB Garamond',
          fontSize: 24,
          fontWeight: 600,
          color: '#722f37',
        },
        sectionSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 12,
          fontWeight: 400,
          color: '#2d1b2e',
        },
        itemName: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 15,
          fontWeight: 600,
          color: '#2d1b2e',
        },
        itemDescription: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 12,
          fontWeight: 400,
          color: '#5a4a5c',
        },
        itemPrice: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 14,
          fontWeight: 600,
          color: '#722f37',
          textAlign: 'right',
        },
        footer: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lato',
          fontSize: 9,
          fontWeight: 400,
          color: '#5a4a5c',
          textAlign: 'center',
        },
      },
      itemSeparator: 'none',
      priceFormat: 'right-aligned',
    },
  },

  // 4. Brunch
  {
    id: nanoid(),
    name: 'Brunch',
    category: 'brunch',
    description: 'Weekend brunch menu with morning favorites and sweet treats',
    tags: ['light-theme', 'elegant', 'multi-section'],
    menuData: {
      title: 'Weekend Brunch',
      subtitle: 'Saturday & Sunday 9am - 3pm',
      footer: '',
      sections: [
        {
          id: nanoid(),
          title: 'Morning Favorites',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Eggs Benedict',
              description: 'Poached eggs, Canadian bacon, English muffin, hollandaise, breakfast potatoes',
              price: '17.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Smoked Salmon Bagel',
              description: 'House-cured salmon, cream cheese, capers, red onion, tomato, everything bagel',
              price: '18.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Farmers Market Omelet',
              description: 'Three eggs, seasonal vegetables, aged cheddar, mixed greens, sourdough toast',
              price: '16.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Avocado Toast',
              description: 'Smashed avocado, heirloom tomatoes, poached eggs, chili flakes, multigrain',
              price: '15.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Sweet Plates',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Brioche French Toast',
              description: 'Thick-cut brioche, maple syrup, whipped butter, fresh berries, powdered sugar',
              price: '15.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Blueberry Pancakes',
              description: 'Buttermilk pancakes, wild blueberries, maple syrup, whipped cream',
              price: '14.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Belgian Waffle',
              description: 'Crispy waffle, strawberries, banana, Nutella drizzle, vanilla ice cream',
              price: '16.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Beverages',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Mimosa',
              description: 'Fresh orange juice, prosecco',
              price: '10.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Bloody Mary',
              description: 'House-made mix, vodka, celery, olives, pickled vegetables',
              price: '12.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Cold Brew Coffee',
              description: 'House-roasted beans, smooth and bold',
              price: '5.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Fresh Pressed Juice',
              description: 'Orange, grapefruit, or green juice',
              price: '7.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Bottomless Specials',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Bottomless Mimosas',
              description: '90 minutes of unlimited mimosas with entrée purchase',
              price: '25.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Bottomless Bellinis',
              description: '90 minutes of unlimited peach or berry bellinis with entrée',
              price: '28.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
      ],
    },
    pageLayout: {
      ...createDefaultPageLayout(),
      pageSize: 'letter',
      orientation: 'portrait',
      margins: { top: 0.57, right: 0.52, bottom: 0.57, left: 0.52 },
      sectionLayouts: [],
      colorScheme: {
        background: '#FFF8F0',
        text: '#3d2e1f',
        accent: '#d4763c',
        border: '#e8d5c0',
      },
      typography: {
        ...createDefaultTypography(),
        menuTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lora',
          fontSize: 48,
          fontWeight: 700,
          color: '#d4763c',
          textAlign: 'center',
        },
        menuSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lora',
          fontSize: 15,
          fontWeight: 400,
          color: '#3d2e1f',
          letterSpacing: 1.5,
          textAlign: 'center',
        },
        sectionTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Lora',
          fontSize: 24,
          fontWeight: 600,
          color: '#d4763c',
        },
        sectionSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 12,
          fontWeight: 400,
          color: '#3d2e1f',
        },
        itemName: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 15,
          fontWeight: 600,
          color: '#3d2e1f',
        },
        itemDescription: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 12,
          fontWeight: 400,
          color: '#6a5a4a',
        },
        itemPrice: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 15,
          fontWeight: 700,
          color: '#d4763c',
          textAlign: 'right',
        },
        footer: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 9,
          fontWeight: 400,
          color: '#6a5a4a',
          textAlign: 'center',
        },
      },
      itemSeparator: 'none',
      priceFormat: 'right-aligned',
    },
  },

  // 5. Craft Beer
  {
    id: nanoid(),
    name: 'Craft Beer',
    category: 'beer',
    description: 'Rotating selection of craft beers on tap and in bottles',
    tags: ['light-theme', 'modern', 'compact', 'multi-section'],
    menuData: {
      title: 'Craft Beer',
      subtitle: 'Rotating Selection',
      footer: '',
      sections: [
        {
          id: nanoid(),
          title: 'On Tap',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Hazy IPA',
              description: 'New England style, juicy citrus and tropical notes • 6.5% ABV',
              price: '8.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'West Coast IPA',
              description: 'Classic hoppy bitterness, pine and grapefruit • 7.2% ABV',
              price: '8.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Belgian Tripel',
              description: 'Spicy, fruity, strong golden ale • 9.0% ABV',
              price: '9.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Oatmeal Stout',
              description: 'Rich chocolate and coffee, smooth body • 5.8% ABV',
              price: '7.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Pilsner',
              description: 'Crisp, clean, Czech-style lager • 4.8% ABV',
              price: '7.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Sour Ale',
              description: 'Tart cherry and raspberry, wild fermented • 5.5% ABV',
              price: '9.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Bottles & Cans',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Imperial Stout',
              description: 'Barrel-aged, bourbon notes, dark chocolate • 11.0% ABV',
              price: '12.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Saison Farmhouse',
              description: 'Earthy, peppery, dry finish • 6.5% ABV',
              price: '8.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Double IPA',
              description: 'Intensely hoppy, resinous, bold • 8.5% ABV',
              price: '9.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Wheat Beer',
              description: 'Banana and clove, refreshing citrus • 5.2% ABV',
              price: '7.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Flights',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'IPA Flight',
              description: 'Four 5oz pours of our rotating IPA selection',
              price: '16.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Brewers Choice',
              description: 'Four 5oz pours selected by our beer expert',
              price: '15.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
      ],
    },
    pageLayout: {
      ...createDefaultPageLayout(),
      pageSize: 'half-letter',
      orientation: 'portrait',
      margins: { top: 0.42, right: 0.36, bottom: 0.42, left: 0.36 },
      sectionLayouts: [],
      colorScheme: {
        background: '#f5f0e8',
        text: '#2a2a2a',
        accent: '#c17817',
        border: '#d8cdb8',
      },
      typography: {
        ...createDefaultTypography(),
        menuTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 36,
          fontWeight: 700,
          color: '#c17817',
          textAlign: 'center',
        },
        menuSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 13,
          fontWeight: 600,
          color: '#2a2a2a',
          letterSpacing: 2,
          textAlign: 'center',
        },
        sectionTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 20,
          fontWeight: 700,
          color: '#c17817',
        },
        sectionSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 11,
          fontWeight: 400,
          color: '#2a2a2a',
        },
        itemName: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 14,
          fontWeight: 700,
          color: '#2a2a2a',
        },
        itemDescription: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 11,
          fontWeight: 400,
          color: '#5a5a5a',
        },
        itemPrice: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 14,
          fontWeight: 700,
          color: '#c17817',
          textAlign: 'right',
        },
        footer: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 9,
          fontWeight: 400,
          color: '#5a5a5a',
          textAlign: 'center',
        },
      },
      itemSeparator: 'none',
      priceFormat: 'right-aligned',
    },
  },

  // 6. Dessert
  {
    id: nanoid(),
    name: 'Dessert',
    category: 'dessert',
    description: 'Decadent desserts and after-dinner specialties',
    tags: ['light-theme', 'elegant', 'compact', 'multi-section'],
    menuData: {
      title: 'Dessert Menu',
      subtitle: 'Sweet Endings',
      footer: '',
      sections: [
        {
          id: nanoid(),
          title: 'Cakes & Tarts',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Dark Chocolate Torte',
              description: 'Flourless dark chocolate cake, raspberry coulis, vanilla whipped cream',
              price: '14.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'New York Cheesecake',
              description: 'Classic creamy cheesecake, graham cracker crust, fresh berry compote',
              price: '13.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Salted Caramel Tart',
              description: 'Buttery tart shell, salted caramel filling, dark chocolate ganache',
              price: '14.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'Ice Cream & Sorbet',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Vanilla Bean Gelato',
              description: 'Madagascar vanilla, rich and creamy Italian-style',
              price: '9.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Dark Chocolate Sorbet',
              description: 'Intense chocolate flavor, dairy-free, velvety smooth',
              price: '9.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Seasonal Fruit Sorbet',
              description: 'Ask your server for today\'s fresh fruit selection',
              price: '8.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Affogato',
              description: 'Vanilla gelato drowned in hot espresso, biscotti',
              price: '11.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: 'After Dinner',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Espresso',
              description: 'Double shot, locally roasted beans',
              price: '4.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Cappuccino',
              description: 'Espresso, steamed milk, foam',
              price: '6.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Digestif Selection',
              description: 'Ask about our grappa, amaro, and port options',
              price: '12.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
      ],
    },
    pageLayout: {
      ...createDefaultPageLayout(),
      pageSize: 'half-letter',
      orientation: 'portrait',
      margins: { top: 0.42, right: 0.36, bottom: 0.42, left: 0.36 },
      sectionLayouts: [],
      colorScheme: {
        background: '#FFF5F5',
        text: '#4a2c2a',
        accent: '#c4667a',
        border: '#f0d5da',
      },
      typography: {
        ...createDefaultTypography(),
        menuTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Dancing Script',
          fontSize: 42,
          fontWeight: 700,
          color: '#c4667a',
          textAlign: 'center',
        },
        menuSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 12,
          fontWeight: 400,
          color: '#4a2c2a',
          letterSpacing: 2,
          textAlign: 'center',
        },
        sectionTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 18,
          fontWeight: 600,
          color: '#c4667a',
        },
        sectionSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 11,
          fontWeight: 400,
          color: '#4a2c2a',
        },
        itemName: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 13,
          fontWeight: 600,
          color: '#4a2c2a',
        },
        itemDescription: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 11,
          fontWeight: 400,
          color: '#7a5a58',
        },
        itemPrice: {
          ...createDefaultFontStyle(),
          fontFamily: 'Montserrat',
          fontSize: 13,
          fontWeight: 700,
          color: '#c4667a',
          textAlign: 'right',
        },
        footer: {
          ...createDefaultFontStyle(),
          fontFamily: 'Open Sans',
          fontSize: 9,
          fontWeight: 400,
          color: '#7a5a58',
          textAlign: 'center',
        },
      },
      itemSeparator: 'none',
      priceFormat: 'right-aligned',
    },
  },

  // 7. Table Tent
  {
    id: nanoid(),
    name: 'Table Tent',
    category: 'table-tent',
    description: 'Promotional table tent for specials and featured items',
    tags: ['dark-theme', 'elegant', 'compact'],
    menuData: {
      title: 'Daily Specials',
      subtitle: '',
      footer: '',
      sections: [
        {
          id: nanoid(),
          title: 'Happy Hour Specials',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Well Drinks',
              description: '4-7pm daily • Your choice of vodka, gin, rum, or whiskey',
              price: '5.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Draft Beer',
              description: '4-7pm daily • Select domestic and craft options',
              price: '4.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'House Wine',
              description: '4-7pm daily • Red, white, or rosé by the glass',
              price: '6.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Appetizer Trio',
              description: '4-7pm daily • Wings, mozzarella sticks, and jalapeño poppers',
              price: '12.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
        {
          id: nanoid(),
          title: "Chef's Picks",
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Truffle Burger',
              description: 'Prime beef, truffle aioli, aged cheddar, arugula, brioche bun, fries',
              price: '22.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Pan-Seared Salmon',
              description: 'Atlantic salmon, lemon butter, asparagus, wild rice pilaf',
              price: '28.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
            {
              id: nanoid(),
              name: 'Tiramisu',
              description: 'House-made Italian classic, espresso-soaked ladyfingers, mascarpone',
              price: '10.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
      ],
    },
    pageLayout: {
      ...createDefaultPageLayout(),
      pageSize: 'table-tent',
      orientation: 'landscape',
      margins: { top: 0.31, right: 0.31, bottom: 0.31, left: 0.31 },
      sectionLayouts: [],
      colorScheme: {
        background: '#1a2332',
        text: '#f0e6d3',
        accent: '#e8b84b',
        border: '#3a4352',
      },
      typography: {
        ...createDefaultTypography(),
        menuTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'DM Serif Display',
          fontSize: 36,
          fontWeight: 700,
          color: '#e8b84b',
          textAlign: 'center',
        },
        menuSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'DM Serif Display',
          fontSize: 14,
          fontWeight: 400,
          color: '#f0e6d3',
          textAlign: 'center',
        },
        sectionTitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'DM Serif Display',
          fontSize: 20,
          fontWeight: 600,
          color: '#e8b84b',
        },
        sectionSubtitle: {
          ...createDefaultFontStyle(),
          fontFamily: 'Inter',
          fontSize: 11,
          fontWeight: 400,
          color: '#f0e6d3',
        },
        itemName: {
          ...createDefaultFontStyle(),
          fontFamily: 'Inter',
          fontSize: 14,
          fontWeight: 700,
          color: '#f0e6d3',
        },
        itemDescription: {
          ...createDefaultFontStyle(),
          fontFamily: 'Inter',
          fontSize: 11,
          fontWeight: 400,
          color: '#d0c6b3',
        },
        itemPrice: {
          ...createDefaultFontStyle(),
          fontFamily: 'Inter',
          fontSize: 14,
          fontWeight: 700,
          color: '#e8b84b',
          textAlign: 'right',
        },
        footer: {
          ...createDefaultFontStyle(),
          fontFamily: 'Inter',
          fontSize: 9,
          fontWeight: 400,
          color: '#d0c6b3',
          textAlign: 'center',
        },
      },
      itemSeparator: 'none',
      priceFormat: 'right-aligned',
    },
  },

  // 8. Cafe
  cafeTemplate,

  // 9. Pizzeria
  pizzeriaTemplate,

  // 10. Sushi Bar
  sushiTemplate,

  // 11. Bakery
  bakeryTemplate,

  // 12. Taqueria
  taqueriaTemplate,

  // 13. Blank Template
  {
    id: nanoid(),
    name: 'Blank',
    category: 'blank',
    description: 'Start from scratch with an empty template',
    tags: ['light-theme'],
    menuData: {
      title: 'Menu Title',
      subtitle: '',
      footer: '',
      sections: [
        {
          id: nanoid(),
          title: 'Section Name',
          subtitle: '',
          footnote: '',
          items: [
            {
              id: nanoid(),
              name: 'Item Name',
              description: 'Item description',
              price: '0.00',
              priceLabel: '',
              tags: [],
              isAvailable: true,
            },
          ],
        },
      ],
    },
    pageLayout: createDefaultPageLayout(),
  },
]

export default templates
